# Juntar datos de aemet

In [19]:
import pandas as pd
import glob

In [20]:
# Obtener todos los archivos CSV en una carpeta
archivos = glob.glob("data/raw/data_aemet/aemet_meses/*.csv")

# Leer y concatenar todos los archivos
df = pd.concat([pd.read_csv(f) for f in archivos])

# Opcional: Ordenar por fecha si hay una columna de tiempo
df = df.sort_values(by="fecha")
df

,fecha,indicativo,nombre,provincia,altitud,tmed,prec,tmin,horatmin,tmax,...,horaracha,presMax,horaPresMax,presMin,horaPresMin,hrMedia,hrMax,horaHrMax,hrMin,horaHrMin
0,2019-01-01,3195,"MADRID, RETIRO",MADRID,667,"6,6","0,0","1,4",07:30,"11,7",...,00:00,"953,9",09,"951,5",05,49.0,68.0,23:50,41.0,14:20
1,2019-01-02,3195,"MADRID, RETIRO",MADRID,667,"6,0","0,0","0,4",06:30,"11,7",...,23:20,"952,5",00,"948,3",16,54.0,74.0,08:20,41.0,14:50
2,2019-01-03,3195,"MADRID, RETIRO",MADRID,667,"7,3","0,0","2,8",07:00,"11,8",...,00:10,"951,4",10,"949,0",05,46.0,54.0,Varias,37.0,15:30
3,2019-01-04,3195,"MADRID, RETIRO",MADRID,667,"5,9","0,0","0,4",08:05,"11,4",...,05:40,"952,9",Varias,"949,9",05,60.0,79.0,09:00,43.0,15:00
4,2019-01-05,3195,"MADRID, RETIRO",MADRID,667,"5,4","0,0","-0,1",08:00,"10,8",...,10:40,"955,2",12,"952,5",00,54.0,72.0,Varias,43.0,14:30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,2025-02-06,3195,"MADRID, RETIRO",MADRID,667,"7,2","0,0","1,9",07:00,"12,5",...,00:30,"952,0",00,"944,8",24,54.0,76.0,23:30,37.0,14:40
129,2025-02-07,3195,"MADRID, RETIRO",MADRID,667,"4,9","7,6","1,2",06:50,"8,6",...,12:30,"944,8",00,"937,5",17,88.0,99.0,Varias,67.0,12:00
130,2025-02-08,3195,"MADRID, RETIRO",MADRID,667,"7,2","0,0","3,0",07:50,"11,4",...,Varias,"946,6",24,"938,3",00,NaN,NaN,NaN,NaN,NaN
131,2025-02-09,3195,"MADRID, RETIRO",MADRID,667,"8,2","0,0","3,3",05:30,"13,2",...,Varias,"948,0",Varias,"944,6",24,82.0,NaN,NaN,NaN,NaN
132,2025-02-10,3195,"MADRID, RETIRO",MADRID,667,"10,4","0,0","7,4",05:00,"13,5",...,12:40,"944,6",00,"939,5",19,78.0,95.0,05:00,64.0,13:40

In [29]:
df.to_csv("data/raw/data_aemet/estacion_3195_data.csv", index=False)

In [27]:
df["fecha"] = pd.to_datetime(df["fecha"])

In [22]:
rango_fechas = pd.date_range(start=df["fecha"].min(), end=df["fecha"].max(), freq="D")

In [30]:
fechas_faltantes = rango_fechas.difference(df["fecha"])
fechas_faltantes

DatetimeIndex([], dtype='datetime64[ns]', freq='D')

In [24]:
nuevafila = {"fecha": "2022-03-14", "indicativo": "3195", "nombre": "MADRID, RETIRO", "provincia": "MADRID", "altitud": 667, "prec": "0,0"}

In [25]:
df = pd.concat([df, pd.DataFrame([nuevafila])], ignore_index=True)

In [28]:
df = df.sort_values(by="fecha")
df

,fecha,indicativo,nombre,provincia,altitud,tmed,prec,tmin,horatmin,tmax,...,horaracha,presMax,horaPresMax,presMin,horaPresMin,hrMedia,hrMax,horaHrMax,hrMin,horaHrMin
0,2019-01-01,3195,"MADRID, RETIRO",MADRID,667,"6,6","0,0","1,4",07:30,"11,7",...,00:00,"953,9",09,"951,5",05,49.0,68.0,23:50,41.0,14:20
1,2019-01-02,3195,"MADRID, RETIRO",MADRID,667,"6,0","0,0","0,4",06:30,"11,7",...,23:20,"952,5",00,"948,3",16,54.0,74.0,08:20,41.0,14:50
2,2019-01-03,3195,"MADRID, RETIRO",MADRID,667,"7,3","0,0","2,8",07:00,"11,8",...,00:10,"951,4",10,"949,0",05,46.0,54.0,Varias,37.0,15:30
3,2019-01-04,3195,"MADRID, RETIRO",MADRID,667,"5,9","0,0","0,4",08:05,"11,4",...,05:40,"952,9",Varias,"949,9",05,60.0,79.0,09:00,43.0,15:00
4,2019-01-05,3195,"MADRID, RETIRO",MADRID,667,"5,4","0,0","-0,1",08:00,"10,8",...,10:40,"955,2",12,"952,5",00,54.0,72.0,Varias,43.0,14:30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2227,2025-02-06,3195,"MADRID, RETIRO",MADRID,667,"7,2","0,0","1,9",07:00,"12,5",...,00:30,"952,0",00,"944,8",24,54.0,76.0,23:30,37.0,14:40
2228,2025-02-07,3195,"MADRID, RETIRO",MADRID,667,"4,9","7,6","1,2",06:50,"8,6",...,12:30,"944,8",00,"937,5",17,88.0,99.0,Varias,67.0,12:00
2229,2025-02-08,3195,"MADRID, RETIRO",MADRID,667,"7,2","0,0","3,0",07:50,"11,4",...,Varias,"946,6",24,"938,3",00,NaN,NaN,NaN,NaN,NaN
2230,2025-02-09,3195,"MADRID, RETIRO",MADRID,667,"8,2","0,0","3,3",05:30,"13,2",...,Varias,"948,0",Varias,"944,6",24,82.0,NaN,NaN,NaN,NaN
2231,2025-02-10,3195,"MADRID, RETIRO",MADRID,667,"10,4","0,0","7,4",05:00,"13,5",...,12:40,"944,6",00,"939,5",19,78.0,95.0,05:00,64.0,13:40

In [18]:
import os

carpeta = "data/raw/data_aemet/aemet_meses"
archivos = [f for f in os.listdir(carpeta) if f.endswith(".csv")]

for archivo in archivos:
    # Extrae los últimos 8 caracteres antes de ".csv"
    nombre_base, extension = os.path.splitext(archivo)
    terminacion = nombre_base[-8:] + ".csv"  # Toma los últimos 8 caracteres
    nuevo_nombre = f"estacion_3195_{terminacion}"

    # Rutas completa de los archivos
    ruta_vieja = os.path.join(carpeta, archivo)
    ruta_nueva = os.path.join(carpeta, nuevo_nombre)
    
    # Renombra el archivo
    os.rename(ruta_vieja, ruta_nueva)
    print(f"Renombrado: {archivo} -> {nuevo_nombre}")

Renombrado: Estacion_3195_AbrSep24.csv -> estacion_3195_AbrSep24.csv
Renombrado: Estacion_3195_AgoEne20.csv -> estacion_3195_AgoEne20.csv
Renombrado: Estacion_3195_AgoEne21.csv -> estacion_3195_AgoEne21.csv
Renombrado: Estacion_3195_DecAbr23.csv -> estacion_3195_DecAbr23.csv
Renombrado: Estacion_3195_EneMay22.csv -> estacion_3195_EneMay22.csv
Renombrado: Estacion_3195_FebJul19.csv -> estacion_3195_FebJul19.csv
Renombrado: Estacion_3195_FebJul20.csv -> estacion_3195_FebJul20.csv
Renombrado: Estacion_3195_FebJun21.csv -> estacion_3195_FebJun21.csv
Renombrado: Estacion_3195_JulDec21.csv -> estacion_3195_JulDec21.csv
Renombrado: Estacion_3195_JunNov22.csv -> estacion_3195_JunNov22.csv
Renombrado: Estacion_3195_MayOct23.csv -> estacion_3195_MayOct23.csv
Renombrado: Estacion_3195_NovMar24.csv -> estacion_3195_NovMar24.csv
Renombrado: Estacion_3195_OctFeb25.csv -> estacion_3195_OctFeb25.csv
Renombrado: Estacion_3195_ridEne19.csv -> estacion_3195_ridEne19.csv